[package]
name = "tpaint_glow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13"
tpaint = { path = "../tpaint" }
glow = "0.12"
log = "0.4"